theme: jekyll-theme-minimal
title: LawConnect
description: Full Stack Lawyer Consultation Platform
show_downloads: false
github:
  repository_url: https://github.com/devlondon47-spec/lawyer
  is_project_page: false
